name: Build and Release Go Binary

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          cd apps/tag-replacer-go
          go build -o tag-replacer-linux .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: apps/tag-replacer-go/tag-replacer-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          cd apps/tag-replacer-go
          go build -o tag-replacer-windows.exe .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: apps/tag-replacer-go/tag-replacer-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          cd apps/tag-replacer-go
          go build -o tag-replacer-macos .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: apps/tag-replacer-go/tag-replacer-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}