name: Extract Version

on:
  workflow_call:
    outputs:
      version:
        description: "Extracted version from tag or 'latest'"
        value: ${{ jobs.extract-version.outputs.version }}

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set version from tag
        id: set-version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi